# Generated by Django 4.2.17 on 2024-12-17 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entertainmentcenter',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='entertainmentcenter',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='entertainmentcenter',
            name='center_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entertainment.centertype'),
        ),
        migrations.AlterField(
            model_name='entertainmentcenter',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entertainmentcenter',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name="Ім'я відвідувача")),
                ('email', models.EmailField(max_length=254, verbose_name='Електронна пошта')),
                ('visit_date', models.DateTimeField(auto_now_add=True, verbose_name='Час відвідування')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='entertainment.entertainmentcenter', verbose_name='Центр')),
            ],
        ),
    ]
