# Generated by Django 4.2.17 on 2024-12-17 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0002_remove_entertainmentcenter_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='center',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='visit_date',
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('entertainment_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='entertainment.entertainmentcenter')),
            ],
        ),
    ]
