# Generated by Django 4.2.17 on 2024-12-17 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0003_remove_visitor_center_remove_visitor_visit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='entertainment_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entertainment.entertainmentcenter'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
